<?php
header('Content-Type: application/json');
error_reporting(0);

// Prevent altering settings from outside the local network
$client_ip = $_SERVER['REMOTE_ADDR'];
if (!empty($_SERVER['HTTP_CF_CONNECTING_IP'])) {
    $client_ip = $_SERVER['HTTP_CF_CONNECTING_IP'];
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $ips = array_map('trim', explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']));
    $client_ip = end($ips);
}

function is_local_ip($ip) {
    if ($ip === '127.0.0.1' || $ip === '::1') {
        return true;
    }
    $ip_num = ip2long($ip);
    if ($ip_num !== false) {
        $private_ranges = [
            ['10.0.0.0', '10.255.255.255'],
            ['172.16.0.0', '172.31.255.255'],
            ['192.168.0.0', '192.168.255.255'],
        ];
        foreach ($private_ranges as $range) {
            $min = ip2long($range[0]);
            $max = ip2long($range[1]);
            if ($ip_num >= $min && $ip_num <= $max) {
                return true;
            }
        }
    }
    return false;
}

if (!is_local_ip($client_ip)) {
    http_response_code(403);
    echo json_encode(['error' => 'Saving overrides is only allowed from the local network.']);
    exit;
}

$raw = file_get_contents('php://input');
$data = json_decode($raw, true);

if (!is_array($data)) {
    $raw_post = $_POST['overrides'] ?? '';
    if ($raw_post) {
        $data = json_decode($raw_post, true);
    }
}

if (!is_array($data)) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid JSON received']);
    exit;
}

$json_str = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
$js_content = "/* Auto-generated by sandbox.php — Highcharts visual overrides */\nwindow.w34HighchartsOverrides = " . $json_str . ";\n";

$target_file = __DIR__ . '/w34highcharts/scripts/sandbox-overrides.js';
if (file_put_contents($target_file, $js_content) === false) {
    http_response_code(500);
    echo json_encode(['error' => 'Failed to write overrides file']);
    exit;
}

echo json_encode(['success' => true, 'overrides' => $data]);
